INSERT INTO STATUSES (ID, `NAME`) VALUES (1, 'active');
INSERT INTO STATUSES (ID, `NAME`) VALUES (0, 'inactive');

INSERT INTO AUTHORS (ID, FIRSTNAME, SECONDNAME, THIRDNAME, BIRTH_DATE, STATUS)
VALUES (1, 'Иванов', 'Иван', 'Иванович', null, 1);

INSERT INTO GENRES (ID, `NAME`) VALUES (1, 'Жанр1');

INSERT INTO BOOKS (ID, `NAME`, CREATE_DATE, DESCRIPTION, `IMAGE`, GENRE, STATUS, AUTHOR)
VALUES (1, 'Книга 1', null, 'Описание', NULL, 1, 1, 1);